spring.application.name=${APP_NAME}
server.port=${APP_PORT}
spring.datasource.url=jdbc:${DB_CONNECTION}://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.sql.init.mode=${SQL_INIT_MODE:never}